### ISSUE TITLE
Theme colors not updated

### ISSUE THREAD

**Issue by aeternesatiatus** [thiagorossener/jekflix-template#34]
I've changed all the theme colors to black: https://github.com/aeternesatiatus/en.hackdown.org/blob/master/src/styl/_variables.styl
and the theme didn't change colors after building: https://keen-elion-331a03.netlify.com/

Any ideas why?

**Comment by thiagorossener** [comment]
@aeternesatiatus have you run `$ gulp`?

**Comment by aeternesatiatus** [comment]
@thiagorossener I did

**Comment by aeternesatiatus** [comment]
Changed every hex to black in the config
and here is the result: https://quizzical-kalam-5d5b42.netlify.com/

**Comment by thiagorossener** [comment]
@aeternesatiatus I can't access your repo to check it out anymore.

*Jekflix Template 2.0* was released a week ago, I'd recommend you to try the new version, once it works a bit different and you're able to change only `theme.yml` and run `gulp build` in order to change all the template colors.

**Comment by aeternesatiatus** [comment]
Alright, thanks! I'll give it a try. It'd be cool if you made a bash script to configure the website :)

**Comment by aeternesatiatus** [comment]
@thiagorossener I've tried Jekflix 2 https://github.com/hackdown-org/jekflix.hackdown.org/  and the colours are still not being updated after building with Jekyll and running gulp build. Any ideas why?

https://eloquent-heisenberg-81825a.netlify.com/

**Comment by thiagorossener** [comment]
@aeternesatiatus version 2 is a little different. You need to change [`theme.yml`](https://github.com/hackdown-org/jekflix.hackdown.org/blob/master/src/yml/theme.yml) file in order to change overall colors. I've just added the theme colors descriptions [here](https://github.com/thiagorossener/jekflix-template/wiki/settings#theme).

The `_config.yml` is generated from the files in [`src/yml/`](https://github.com/hackdown-org/jekflix.hackdown.org/tree/master/src/yml). So, if you change it, it will get overwritten when running `gulp build`.

I'm thinking about to create a _gem_ to make it easier for people update the theme, still need to study more about that though.

**Comment by aeternesatiatus** [comment]
Right, maybe remove the colour parameters in the config.yml if they get overwritten then? Anyways I'll give it a try and let you know :)

**Comment by aeternesatiatus** [comment]
Works well! Thanks a lot. You can close the issue!

**Comment by thiagorossener** [comment]
@aeternesatiatus awesome! I had removed this before, but some people were having trouble customizing and publishing it on GitHub pages directly, once you can't run `gulp build` there.

I'll add a comment to the docs about that though.
