### ISSUE TITLE
index.html Hero "no-padding" Issue

### ISSUE THREAD

**Issue by anisabek** [thiagorossener/jekflix-template#37]
Hello, I am having an issue with Hero feature. Although it's been set to : true it's not showing the first article in posts.

**Comment by thiagorossener** [comment]
@anisabek have you run `gulp`?

**Comment by anisabek** [comment]
> @anisabek have you run `gulp`?

I had some issues on my device so I pushed the project to my github and I am editing it from here.
Here is the link to my github page website: https://anisabek.github.io/
The first article seems to be aligned with the rest of articles.

**Comment by thiagorossener** [comment]
Well, here is the thing. You need to have a `_config.yml` file in the root of your website.

I removed this from _Jekflix Template 2.0_ because these files are built from several `.yml` files located in `src/yml/`.

When you change the files in the `src/yml/` folder and run `gulp` or `gulp build`, it generates the `_config.yml` in the project root.

That said, GitHub pages only build Jekyll, it doesn't run `gulp` before build it, so that's the reason why all your icons have no color, you had to change your website name by editing the HTML, the hero feature doesn't work and so on.

To sort this out, just do exactly what I did in [this commit](https://github.com/thiagorossener/jekflix-template/commit/a7f640e009b65891d8cde4e8d9bf0c6e781e0513), which is remove a couple lines from `.gitignore` and create a `_config.yml`.

Then, for anything you need to change in your website, just change it in `_config.yml`.

But ***be careful***. Bear in mind that at the moment you run `gulp` or `gulp build`, this file will get overwritten and the settings from the files in `src/yml/` will get into its place.

**Comment by anisabek** [comment]
thanks a alot, it worked
