### ISSUE TITLE
ThemeColor not reflected

### ISSUE THREAD

**Issue by noraj** [thiagorossener/jekflix-template#54]
I changed `themeColor` to some orange. Ok some buttons were changed but this page breaker thing have the red color hardcoded:

![image](https://user-images.githubusercontent.com/16578570/70065331-3b9f1280-15eb-11ea-8fb0-517d20800413.png)

![image](https://user-images.githubusercontent.com/16578570/70065252-0eeafb00-15eb-11ea-9d5d-3d5b1a1a845a.png)

it seems the tag page also keep the red:

![image](https://user-images.githubusercontent.com/16578570/70065463-76a14600-15eb-11ea-85d9-fa4c994f60bd.png)

I removed `_site`, re `bundle build` and then gulp but the red stays.

Its is also hardcoded in SVG:

```
./src/img/star.svg:<path style="fill:#ff0a16;" d="M44,24c0,11.045-8.955,20-20,20S4,35.045,4,24S12.955,4,24,4S44,12.955,44,24z"/>                                                               
```

I also changed it in `./admin/config.yml` but all keeps red in admin panel.

**Comment by thiagorossener** [comment]
Hi @noraj, the star SVG was hardcoded as you said and I just fixed it, thanks for pointing this out.

As for the other things, I'm afraid you can't change the colors this way.

In order to allow a total theme change, I had to add some processes. So, the file you need to change is just `src/yml/theme.yml` and then run `gulp`. You don't need to run anything more than that.

This will create the file `theme.json` in `src/styl/` that will be used in CSS to change those components you showed.

More regarding documentation you can see [here](https://github.com/thiagorossener/jekflix-template/wiki/settings#theme).

**Comment by noraj** [comment]
Thanks @thiagorossener
