### ISSUE TITLE
How to Change the Color and Font of the text in blog

### ISSUE THREAD

**Issue by chaitanyasaxena066** [thiagorossener/jekflix-template#82]
Hello 

I'm writing the blog I want to know that is there is any way how to change the color of the text in blog like I want to change color to blue rather then black how can we do that  and also how to change the fonts to different family ?

**Comment by thiagorossener** [comment]
Hey @chaitanyasaxena066, follow [these instructions ](https://github.com/thiagorossener/jekflix-template/wiki/settings#theme) to change the theme (including text colors).

In order to change the font family, you can't do this if you're using the `gem`, but in the case you're cloning the repo, just change the `mainFont` function in the `_sass/_mixins.scss`.

**Comment by chaitanyasaxena066** [comment]
Ok thanks a lot for your help I will surely look on this
